# naccho_configuration.R
# 
# This script is where NACCHO staff members can make modifications to XXX in
# one place. Then they can re-run the scripts to create:
# 
# 1. urban/rural LHD counts
# 2. ACS totals
# 3. ACS estimates from IPF 

## ---- Load required packages ----
require(glue)

## ---- !!!USER PROVIDED VALUES!!! ----
## These two variables must be set by the person running the script, IF something has changed since the last time the script was run.

## SET THE LHD VINTAGE
## We use this on our output file names to help NACCHO staff determine the LHD vintage for the estimates
lhd_vintage <- "lhd2022"

## SET THE ACS DATASET 
## The ACS_dataset is the 5-year ACS dataset from which you want to generate LHD totals. To update this variable
## to a new 5-year dataset, you just need to the change the two years in the string (e.g., change 2017 to 2018 and 2021 to 2022).

## New ACS datasets will have a similar name to the one included below. E.g.:
## 2018_2022_ACS5a
## 2019_2023_ACS5a
## 2020_2024_ACS5a
acs_dataset <- "2017_2021_ACS5a"

## ---- Set scientific notations to off ----
options(scipen = 999)

## ---- Source R files to create require IPF functions ----
source("R/create-estimates/ipf-code/ipf2df.txt")

## ---- Constants ----

## List of state abbreviations. We add DC to the vector and remove Rhode Island because RI has
## no LHDs.
state_abbr <- c(state.abb, "DC")
state_abbr <- setdiff(state_abbr, "RI")

## Data directory path. This is the path to the main directory that contains all required data files.
user <- "dvanriper" # We may not need this depending on how we set up the system on the NACCHO computing system
dat_dir <- glue("/Users/{user}/Box Sync/NACCHO GIS/data_working")

## Output data directory path for ACS and urban/rural estimates. These are the paths where output files are written.
acs_output_dir <- glue("{dat_dir}/output-data/{acs_dataset}")
ur_output_dir <- glue("{dat_dir}/output-data/urban_rural")

## Create the ACS output data directory if it doesn't already exist
if(!dir.exists(acs_output_dir)){
  dir.create(acs_output_dir, recursive= TRUE)
}

## Create the urban/rural output data directory if it doesn't already exist
if(!dir.exists(ur_output_dir)){
  dir.create(ur_output_dir, recursive= TRUE)
}

## ---- Constants for urban/rural processing ----

## Paths to the geocorr crosswalks - these crosswalks provide us with the urban/rural designation for each 2020 census block
file_geocorr1 <- glue(dat_dir, "/tables/geocorr/geocorr2022_2310905557_HI.csv.gz")
file_geocorr2 <- glue(dat_dir, "/tables/geocorr/geocorr2022_2310909397_MS.csv.gz")
file_geocorr3 <- glue(dat_dir, "/tables/geocorr/geocorr2022_2310908189_PA.csv.gz")
file_geocorr4 <- glue(dat_dir, "/tables/geocorr/geocorr2022_2310901017_WY.csv.gz")

## Path to the 2020 census block that provides the total population for each block
## Since we use this with the geocorr data, I think it would be best to move the gzip file
## to that directory. 
file_blkpop20 <- glue(dat_dir, "/tables/geocorr/nhgis1726_ds248_2020_block.csv.gz")

## ---- Constants for ACS totals ----
## These constants are used to generate the ACS totals from the tables that contains Place070 data.

# The ACS provides Place070 data for four tables - Total Population, Race, Housing Units, Housing Tenure
place070_data_tables <- c("B01003", "B02001", "B25001", "B25003")

# ACS download directory - this directory will hold the ACS data file containing the Total Population, Race, Housing Units, and Housing Tenure info
download_acs_totals_dir <- glue(dat_dir, "/tables/nhgis-csv/{acs_dataset}/acs_totals")

## ---- Constants for the ACS estimates generated by Iterative Proportional Fitting ----
## Sex by Age
# ACS table
acs_sexage <- "B01001"

# Download directory
download_acs_sexage_dir <- glue(dat_dir, "/tables/nhgis-csv/{acs_dataset}/sexage")

## Household Income
# ACS table
acs_hhincome <- "B19001"

# Download directory
download_acs_hhincome_dir <- glue(dat_dir, "/tables/nhgis-csv/{acs_dataset}/hhincome")

## Owner-Occupied Housing Value
# ACS table
acs_ownoccvalue <- "B25075"

# Download directory
download_acs_ownoccvalue_dir <- glue(dat_dir, "/tables/nhgis-csv/{acs_dataset}/ownoccvalue")

## Renter-Occupied Gross Rent
# ACS table
acs_grossrent <- "B25063"

# Download directory
download_acs_grossrent_dir <- glue(dat_dir, "/tables/nhgis-csv/{acs_dataset}/grossrent")
